"""Update Click model columns

Revision ID: 9b252e4e6a14
Revises: 
Create Date: 2025-04-02 08:43:22.683731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b252e4e6a14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamps', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('timestamps')
        batch_op.drop_column('data')
        batch_op.drop_column('action')

    # ### end Alembic commands ###
